= swaylockd(1)
:doctype: manpage
:repo-uri: https://github.com/jirutka/swaylockd
:issues-uri: {repo-uri}/issues
ifdef::backend-manpage[]
:basedir-spec: pass:q["`XDG Base Directory Specification`"]
:flock: pass:q[*flock(2)*]
:swaylock: pass:q[*swaylock(1)*]
endif::[]
ifndef::backend-manpage[]
:basedir-spec: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html[XDG Base Directory Specification]
:flock: https://www.mankier.com/2/flock[flock(2)]
:swaylock: https://www.mankier.com/1/swaylock[swaylock(1)]
endif::[]

== NAME

swaylockd - launch swaylock(1) and re-launch if it dies


== SYNOPSIS

*swaylockd* [options...]

All options are directly passed to {swaylock}.


== DESCRIPTION

*swaylockd* is a dumb launcher to spawn {swaylock} and ensure it`'s running no matter what -- it immediately restarts {swaylock} if terminated by a signal (e.g. the process crashed) and also blocks all signals (except `SIGKILL` and `SIGSTOP`).
It also ensures that only one instance per user is running (using *flock(2)*).

*IMPORTANT*: *swaylockd* is not compatible with {swaylock} option *--daemonize*!


== ENVIRONMENT

*XDG_RUNTIME_DIR*::
This variable must be set and contain the path to the existing directory where the lock file will be created.
Refer to {basedir-spec} for more information.


== FILES

*${XDG_RUNTIME_DIR}/swaylockd.lock*::
A lock file created when *swaylockd* is executed and removed right before it quits.


== LOGGING

Error messages generated by *swaylockd* are printed to STDERR and logged to syslog with ident string "`swaylockd`" and facility code 1 (user).


== HISTORY

*swaylockd* has been developed mainly as a workaround for the {swaylock} stability issues (see e.g. issue https://github.com/swaywm/swaylock/issues/181[#181]).

{swaylock} is a critical piece of security software -- as a screen locker, any bug in the program that causes it to crash will cause the screen to unlock.
As soon as {swaylock} is no longer running, the screen is no longer locked.
Therefore, great care must be taken to ensure that it never crash.


== AUTHORS

Jakub Jirutka


== REPORTING BUGS

Report bugs to the project`'s issue tracker at {issues-uri}.


== SEE ALSO

{swaylock}
